import React from 'react';
import './StudentIDCard.css';
import { useLanguage } from '../../context/LanguageContext';

const StudentIDCard = () => {
    const { language } = useLanguage();
    
    // Mock user data - in real app, these would come from AuthContext
    const student = {
        name: "Aarav Sharma",
        id: "NSGI-2024-0892",
        class: "Class 10-A",
        dob: "12/05/2009",
        validUntil: "March 2025",
        bloodGroup: "O+",
        house: "Red House"
    };

    return (
        <div className="id-card-container">
            <div className="holographic-card">
                <div className="card-glare"></div>
                <div className="card-header">
                    <div className="school-logo">🏢</div>
                    <div className="school-info">
                        <h2>NSGI ACADEMY</h2>
                        <p>Shaping Futures, Building Leaders</p>
                    </div>
                </div>

                <div className="card-body">
                    <div className="profile-section">
                        <div className="photo-frame">
                            <div className="photo-placeholder-icon">👤</div>
                        </div>
                        <div className="scan-line"></div>
                    </div>

                    <div className="info-section">
                        <div className="info-row">
                            <label>{language === 'hi' ? 'नाम' : 'NAME'}</label>
                            <span>{student.name}</span>
                        </div>
                        <div className="info-row">
                            <label>{language === 'hi' ? 'छात्र आईडी' : 'STUDENT ID'}</label>
                            <span className="id-text">{student.id}</span>
                        </div>
                        <div className="info-grid">
                            <div className="info-row">
                                <label>{language === 'hi' ? 'कक्षा' : 'CLASS'}</label>
                                <span>{student.class}</span>
                            </div>
                            <div className="info-row">
                                <label>{language === 'hi' ? 'रक्त समूह' : 'BLOOD GP'}</label>
                                <span>{student.bloodGroup}</span>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="card-footer">
                    <div className="qr-container">
                        <div className="qr-box">
                            {/* Simulated QR Pattern */}
                            {[...Array(9)].map((_, i) => <div key={i} className="qr-pixel"></div>)}
                        </div>
                    </div>
                    <div className="validity">
                        <label>VALID UNTIL</label>
                        <span>{student.validUntil}</span>
                    </div>
                    <div className="security-seal">OFFICIAL</div>
                </div>
            </div>

            <div className="card-actions">
                <button className="download-btn">📥 {language === 'hi' ? 'आईडी डाउनलोड करें' : 'Download Digital ID'}</button>
                <p className="hint">This is a verified digital credential generated by NSGI Systems.</p>
            </div>
        </div>
    );
};

export default StudentIDCard;
